name: Build and deploy Python app to Azure Web App - pocragweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (no virtualenv, for Azure compatibility)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Opcional: agregar pruebas aquí si se requiere
      # - name: Run tests
      #   run: pytest

      - name: Prepare artifact (exclude unnecessary files)
        run: |
          echo "Preparando archivos para despliegue..."
          mkdir deploy
          cp -r * deploy/
          rm -rf deploy/venv || true
          rm -rf deploy/__pycache__ || true

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09BD7736BB67463881C07753D2E55FDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9747B8F898BF4805B2A3817A6620DB30 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EACE93B3FC845FCBCB9DCE50066E470 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pocragweb'
          slot-name: 'Production'
          package: .

