name: Build and deploy Python app to Azure Web App - pocragweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libnspr4 \
            libxss1 \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libxkbcommon0 \
            libdrm2 \
            libxext6 \
            libxfixes3 \
            libpango-1.0-0 \
            libcairo2 \
            fonts-liberation \
            libappindicator3-1 \
            libnss3-tools \
            lsb-release \
            xdg-utils \
            wget \
            unzip

      - name: Set up Chrome and Chromedriver manually
        run: |
          mkdir -p bin
          
          # Install Chrome
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chrome-linux64.zip -O chrome.zip
          unzip chrome.zip
          mv chrome-linux64/chrome bin/google-chrome
          chmod +x bin/google-chrome
          rm -rf chrome.zip chrome-linux64

          # Install Chromedriver
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chromedriver-linux64.zip -O chromedriver.zip
          unzip chromedriver.zip
          mv chromedriver-linux64/chromedriver bin/chromedriver
          chmod +x bin/chromedriver
          rm -rf chromedriver.zip chromedriver-linux64

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23B0BF1561E84071B1118AC0A28CFAA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D0853879A594DCDB325D6865B71305C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_38FF3ECAB2184C8A98B0C65C735F6059 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pocragweb'
          slot-name: 'Production'
