name: Build and deploy Python app to Azure Web App - pocragweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean up large or unnecessary files before packaging
        run: |
          rm -rf venv __pycache__ *.ipynb *.csv *.pkl *.tar.gz *.zip *.log

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            static/
            !venv/
            !__pycache__/
            !*.ipynb
            !*.csv
            !*.pkl
            !*.tar.gz
            !*.zip
            !*.log

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A40BF998BDA4489687589EEC8F255993 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E18B6FFFACEA479684C9DCB93AB29272 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1C10EED7A3E241A9A45F3D67B4A4FA4C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pocragweb'
          slot-name: 'Production'
