name: Build and deploy Python app to Azure Web App - pocragweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies, Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq \
            libnss3 libnspr4 libatk-bridge2.0-0 libxss1 \
            libgbm1 libxcomposite1 libxcursor1 libxdamage1 \
            libxi6 libxrandr2 libpango-1.0-0 libcairo2 \
            libfontconfig1 libfreetype6 libx11-xcb1 libxcb1 \
            libgtk-3-0

          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+")
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | select(.version | startswith(\"$CHROME_VERSION\")) | .url" | head -n 1)

          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Error: No matching ChromeDriver found for Chrome version $CHROME_VERSION"
            exit 1
          fi

          wget -O chromedriver.zip "$CHROMEDRIVER_VERSION"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          echo "✅ Chrome version:"
          google-chrome --version
          echo "✅ Chromedriver version:"
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23B0BF1561E84071B1118AC0A28CFAA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D0853879A594DCDB325D6865B71305C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_38FF3ECAB2184C8A98B0C65C735F6059 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pocragweb'
          slot-name: 'Production'
